run:
  tests: true
  build-tags:
    - bench
    - !bench
  run:
    skip-dirs-use-default: true

  skip-files:
    - ".*\\.sqlc\\.go$"
    - "db/models.go"
    - "db/querier.go"
    - "db/db.go"

linters-settings:
  funlen:
    lines: 150
    statements: 80
  govet:
    # Report about shadowed variables.
    # Default: false
    check-shadowing: true
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
  exclude-dirs:
    - data
    - data/pgdata
  exclude-files:
    - ".*_gen\\.go$"
    - ".*\\.sql\\.go$"
    - "querier\\.go$"
    - "db\\.go$"
    - "models\\.go$"
    - data/pgdata/.*
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
