// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaOrder struct {
	IDOrderMain int32          `json:"idOrderMain"`
	IDUserF     int32          `json:"idUserF"`
	OrderDate   pgtype.Date    `json:"orderDate"`
	TotalAmount pgtype.Numeric `json:"totalAmount"`
}

type SchemaOrderProduct struct {
	IDOrderF   int32 `json:"idOrderF"`
	IDProductF int32 `json:"idProductF"`
	Quantity   int32 `json:"quantity"`
}

type SchemaProduct struct {
	IDProductMain int32          `json:"idProductMain"`
	NameProduct   string         `json:"nameProduct"`
	Price         pgtype.Numeric `json:"price"`
}

type SchemaUser struct {
	IDUserMain int32  `json:"idUserMain"`
	NameUser   string `json:"nameUser"`
	Email      string `json:"email"`
	Password   string `json:"password"`
}
