// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaOrder struct {
	IDOrderMain int32          `json:"id_order_main"`
	IDUserF     int32          `json:"id_user_f"`
	OrderDate   pgtype.Date    `json:"order_date"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

type SchemaOrderProduct struct {
	IDOrderF   int32 `json:"id_order_f"`
	IDProductF int32 `json:"id_product_f"`
	Quantity   int32 `json:"quantity"`
}

type SchemaProduct struct {
	IDProductMain int32          `json:"id_product_main"`
	NameProduct   string         `json:"name_product"`
	Price         pgtype.Numeric `json:"price"`
}

type SchemaUser struct {
	IDUserMain int32  `json:"id_user_main"`
	NameUser   string `json:"name_user"`
	Email      string `json:"email"`
	Password   string `json:"password"`
}
