// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	DeleteUser(ctx context.Context, idUserMain int32) error
	GetOrdersByUser(ctx context.Context, idUserF int32) ([]GetOrdersByUserRow, error)
	GetProductsByPriceRange(ctx context.Context, arg GetProductsByPriceRangeParams) ([]SchemaProduct, error)
	GetUserByEmail(ctx context.Context, email string) (SchemaUser, error)
	GetUserByID(ctx context.Context, idUserMain int32) (GetUserByIDRow, error)
	GetUserSpendingMetrics(ctx context.Context) ([]GetUserSpendingMetricsRow, error)
	GetUsers(ctx context.Context) ([]GetUsersRow, error)
	GetUsersByPasswordPattern(ctx context.Context, password string) ([]GetUsersByPasswordPatternRow, error)
	UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error
}

var _ Querier = (*Queries)(nil)
